// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: game-proto/game.proto

package game

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on HelloWorldRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *HelloWorldRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HelloWorldRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HelloWorldRequestMultiError, or nil if none found.
func (m *HelloWorldRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HelloWorldRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return HelloWorldRequestMultiError(errors)
	}

	return nil
}

// HelloWorldRequestMultiError is an error wrapping multiple validation errors
// returned by HelloWorldRequest.ValidateAll() if the designated constraints
// aren't met.
type HelloWorldRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HelloWorldRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HelloWorldRequestMultiError) AllErrors() []error { return m }

// HelloWorldRequestValidationError is the validation error returned by
// HelloWorldRequest.Validate if the designated constraints aren't met.
type HelloWorldRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HelloWorldRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HelloWorldRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HelloWorldRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HelloWorldRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HelloWorldRequestValidationError) ErrorName() string {
	return "HelloWorldRequestValidationError"
}

// Error satisfies the builtin error interface
func (e HelloWorldRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHelloWorldRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HelloWorldRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HelloWorldRequestValidationError{}

// Validate checks the field values on HelloWorldReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *HelloWorldReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HelloWorldReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HelloWorldReplyMultiError, or nil if none found.
func (m *HelloWorldReply) ValidateAll() error {
	return m.validate(true)
}

func (m *HelloWorldReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return HelloWorldReplyMultiError(errors)
	}

	return nil
}

// HelloWorldReplyMultiError is an error wrapping multiple validation errors
// returned by HelloWorldReply.ValidateAll() if the designated constraints
// aren't met.
type HelloWorldReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HelloWorldReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HelloWorldReplyMultiError) AllErrors() []error { return m }

// HelloWorldReplyValidationError is the validation error returned by
// HelloWorldReply.Validate if the designated constraints aren't met.
type HelloWorldReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HelloWorldReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HelloWorldReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HelloWorldReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HelloWorldReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HelloWorldReplyValidationError) ErrorName() string { return "HelloWorldReplyValidationError" }

// Error satisfies the builtin error interface
func (e HelloWorldReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHelloWorldReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HelloWorldReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HelloWorldReplyValidationError{}
