// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.3
// - protoc             v4.25.0
// source: game-proto/game.proto

package game

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGameHelloWorld = "/game.v1.Game/HelloWorld"

type GameHTTPServer interface {
	HelloWorld(context.Context, *HelloWorldRequest) (*HelloWorldReply, error)
}

func RegisterGameHTTPServer(s *http.Server, srv GameHTTPServer) {
	r := s.Route("/")
	r.GET("/hello/world", _Game_HelloWorld0_HTTP_Handler(srv))
}

func _Game_HelloWorld0_HTTP_Handler(srv GameHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in HelloWorldRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGameHelloWorld)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.HelloWorld(ctx, req.(*HelloWorldRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*HelloWorldReply)
		return ctx.Result(200, reply)
	}
}

type GameHTTPClient interface {
	HelloWorld(ctx context.Context, req *HelloWorldRequest, opts ...http.CallOption) (rsp *HelloWorldReply, err error)
}

type GameHTTPClientImpl struct {
	cc *http.Client
}

func NewGameHTTPClient(client *http.Client) GameHTTPClient {
	return &GameHTTPClientImpl{client}
}

func (c *GameHTTPClientImpl) HelloWorld(ctx context.Context, in *HelloWorldRequest, opts ...http.CallOption) (*HelloWorldReply, error) {
	var out HelloWorldReply
	pattern := "/hello/world"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGameHelloWorld))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
