server:
  machineId: ''
  http:
    addr: 0.0.0.0:8080
    timeout: 20s
    # service path prefix, check permission will use it
    path: '/layout'
    # use nginx auth_request, disable this
    permission: false
  grpc:
    addr: 0.0.0.0:8180
    timeout: 20s
    health: false
    permission: true
  language: 'en'
  idempotent: true
  validate: true
data:
  database:
    driver: mysql
    endpoint: '127.0.0.1:3306'
    # dsn: 'root:root@tcp(127.0.0.1:3306)/layout?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
    username: 'root'
    password: 'root'
    schema: 'layout'
    query: 'charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
#    tenants:
#      layout.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/layout?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms}'
#      layout2.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/layout2?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
#      layout3.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/layout3?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
#      layout4.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/layout4?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
  redis:
    # redis dsn like this:
    # redis://[:password@]host[:port][/dbnumber]
    # redis://[:password@]host1[:port][,host2:[:port]][,hostN:[:port]][?master=masterName&sentinel=true]
    dsn: 'redis://127.0.0.1:6379/0'
tracer:
  enable: false
  otlp:
    # how to run a otel-collector? see this: https://github.com/SigNoz/signoz/blob/develop/deploy/README.md#using-docker-compose
    endpoint: '127.0.0.1:4317'
    insecure: true
  stdout:
    prettyPrint: false
tasks:
#  - category: task1
#    uuid: id1
#    expr: '0/1 * * * ?'
#  - category: task2
#    uuid: id2
#    expr: '0/5 * * * ?'
