server:
  prod: false
  machineId: ''
  http:
    addr: 0.0.0.0:8080
    timeout: 20s
  grpc:
    addr: 0.0.0.0:8180
    timeout: 20s
  language: 'en'
  idempotent: true
  validate: true
  # disable biz.Cache or not
  nocache: false
data:
  database:
    driver: mysql
    # dsn: 'root:root@tcp(127.0.0.1:3306)/layout?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
    dsn: ''
    endpoint: '127.0.0.1:3306'
    username: 'root'
    password: 'passwd'
    schema: 'layout'
    query: 'charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
#    tenants:
#      layout.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/layout?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms}'
#      layout2.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/layout2?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
#      layout3.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/layout3?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
#      layout4.go-cinch.top: 'root:root@tcp(127.0.0.1:3306)/layout4?charset=utf8mb4&collation=utf8mb4_general_ci&parseTime=True&loc=Local&timeout=10000ms'
  redis:
    # redis dsn like this:
    # redis://[:password@]host[:port][/dbnumber]
    # redis://[:password@]host1[:port][,host2:[:port]][,hostN:[:port]][?master=masterName&sentinel=true]
    dsn: 'redis://127.0.0.1:6379/0'
