// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"github.com/golang-module/carbon/v2"
)

const TableNameGame = "game"

// Game mapped from table <game>
type Game struct {
	ID        uint64          `gorm:"column:id;primaryKey;autoIncrement:true;comment:auto increment id" json:"id,string"`
	CreatedAt carbon.DateTime `gorm:"column:created_at;comment:create time" json:"createdAt"`
	UpdatedAt carbon.DateTime `gorm:"column:updated_at;comment:update time" json:"updatedAt"`
	Name      string          `gorm:"column:name;comment:name" json:"name"`
}

// TableName Game's table name
func (*Game) TableName() string {
	return TableNameGame
}
