// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.5.0
// - protoc             v3.17.3
// source: helloworld/v1/helloword.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationHelloworldCreateGreeter = "/helloworld.v1.Helloworld/CreateGreeter"
const OperationHelloworldCreateGreeterWithCache = "/helloworld.v1.Helloworld/CreateGreeterWithCache"
const OperationHelloworldDeleteGreeter = "/helloworld.v1.Helloworld/DeleteGreeter"
const OperationHelloworldDeleteGreeterWithCache = "/helloworld.v1.Helloworld/DeleteGreeterWithCache"
const OperationHelloworldGetGreeter = "/helloworld.v1.Helloworld/GetGreeter"
const OperationHelloworldGetGreeterWithCache = "/helloworld.v1.Helloworld/GetGreeterWithCache"
const OperationHelloworldListGreeter = "/helloworld.v1.Helloworld/ListGreeter"
const OperationHelloworldListGreeterWithCache = "/helloworld.v1.Helloworld/ListGreeterWithCache"
const OperationHelloworldUpdateGreeter = "/helloworld.v1.Helloworld/UpdateGreeter"
const OperationHelloworldUpdateGreeterWithCache = "/helloworld.v1.Helloworld/UpdateGreeterWithCache"

type HelloworldHTTPServer interface {
	CreateGreeter(context.Context, *CreateGreeterRequest) (*CreateGreeterReply, error)
	CreateGreeterWithCache(context.Context, *CreateGreeterRequest) (*CreateGreeterReply, error)
	DeleteGreeter(context.Context, *DeleteGreeterRequest) (*DeleteGreeterReply, error)
	DeleteGreeterWithCache(context.Context, *DeleteGreeterRequest) (*DeleteGreeterReply, error)
	GetGreeter(context.Context, *GetGreeterRequest) (*GetGreeterReply, error)
	GetGreeterWithCache(context.Context, *GetGreeterRequest) (*GetGreeterReply, error)
	ListGreeter(context.Context, *ListGreeterRequest) (*ListGreeterReply, error)
	ListGreeterWithCache(context.Context, *ListGreeterRequest) (*ListGreeterReply, error)
	UpdateGreeter(context.Context, *UpdateGreeterRequest) (*UpdateGreeterReply, error)
	UpdateGreeterWithCache(context.Context, *UpdateGreeterRequest) (*UpdateGreeterReply, error)
}

func RegisterHelloworldHTTPServer(s *http.Server, srv HelloworldHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/greeter", _Helloworld_CreateGreeter0_HTTP_Handler(srv))
	r.PATCH("/v1/greeter/{id}", _Helloworld_UpdateGreeter0_HTTP_Handler(srv))
	r.PUT("/v1/greeter/{id}", _Helloworld_UpdateGreeter1_HTTP_Handler(srv))
	r.DELETE("/v1/greeter/{id}", _Helloworld_DeleteGreeter0_HTTP_Handler(srv))
	r.GET("/v1/greeter/{id}", _Helloworld_GetGreeter0_HTTP_Handler(srv))
	r.GET("/v1/greeter", _Helloworld_ListGreeter0_HTTP_Handler(srv))
	r.POST("/v1/greeter_with_cache", _Helloworld_CreateGreeterWithCache0_HTTP_Handler(srv))
	r.PATCH("/v1/greeter_with_cache/{id}", _Helloworld_UpdateGreeterWithCache0_HTTP_Handler(srv))
	r.PUT("/v1/greeter_with_cache/{id}", _Helloworld_UpdateGreeterWithCache1_HTTP_Handler(srv))
	r.DELETE("/v1/greeter_with_cache/{id}", _Helloworld_DeleteGreeterWithCache0_HTTP_Handler(srv))
	r.GET("/v1/greeter_with_cache/{id}", _Helloworld_GetGreeterWithCache0_HTTP_Handler(srv))
	r.GET("/v1/greeter_with_cache", _Helloworld_ListGreeterWithCache0_HTTP_Handler(srv))
}

func _Helloworld_CreateGreeter0_HTTP_Handler(srv HelloworldHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateGreeterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHelloworldCreateGreeter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateGreeter(ctx, req.(*CreateGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateGreeterReply)
		return ctx.Result(200, reply)
	}
}

func _Helloworld_UpdateGreeter0_HTTP_Handler(srv HelloworldHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateGreeterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHelloworldUpdateGreeter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateGreeter(ctx, req.(*UpdateGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateGreeterReply)
		return ctx.Result(200, reply)
	}
}

func _Helloworld_UpdateGreeter1_HTTP_Handler(srv HelloworldHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateGreeterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHelloworldUpdateGreeter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateGreeter(ctx, req.(*UpdateGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateGreeterReply)
		return ctx.Result(200, reply)
	}
}

func _Helloworld_DeleteGreeter0_HTTP_Handler(srv HelloworldHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteGreeterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHelloworldDeleteGreeter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteGreeter(ctx, req.(*DeleteGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteGreeterReply)
		return ctx.Result(200, reply)
	}
}

func _Helloworld_GetGreeter0_HTTP_Handler(srv HelloworldHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGreeterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHelloworldGetGreeter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetGreeter(ctx, req.(*GetGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetGreeterReply)
		return ctx.Result(200, reply)
	}
}

func _Helloworld_ListGreeter0_HTTP_Handler(srv HelloworldHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListGreeterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHelloworldListGreeter)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListGreeter(ctx, req.(*ListGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListGreeterReply)
		return ctx.Result(200, reply)
	}
}

func _Helloworld_CreateGreeterWithCache0_HTTP_Handler(srv HelloworldHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateGreeterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHelloworldCreateGreeterWithCache)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateGreeterWithCache(ctx, req.(*CreateGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateGreeterReply)
		return ctx.Result(200, reply)
	}
}

func _Helloworld_UpdateGreeterWithCache0_HTTP_Handler(srv HelloworldHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateGreeterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHelloworldUpdateGreeterWithCache)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateGreeterWithCache(ctx, req.(*UpdateGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateGreeterReply)
		return ctx.Result(200, reply)
	}
}

func _Helloworld_UpdateGreeterWithCache1_HTTP_Handler(srv HelloworldHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateGreeterRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHelloworldUpdateGreeterWithCache)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateGreeterWithCache(ctx, req.(*UpdateGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateGreeterReply)
		return ctx.Result(200, reply)
	}
}

func _Helloworld_DeleteGreeterWithCache0_HTTP_Handler(srv HelloworldHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteGreeterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHelloworldDeleteGreeterWithCache)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteGreeterWithCache(ctx, req.(*DeleteGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteGreeterReply)
		return ctx.Result(200, reply)
	}
}

func _Helloworld_GetGreeterWithCache0_HTTP_Handler(srv HelloworldHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetGreeterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHelloworldGetGreeterWithCache)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetGreeterWithCache(ctx, req.(*GetGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetGreeterReply)
		return ctx.Result(200, reply)
	}
}

func _Helloworld_ListGreeterWithCache0_HTTP_Handler(srv HelloworldHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListGreeterRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHelloworldListGreeterWithCache)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListGreeterWithCache(ctx, req.(*ListGreeterRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListGreeterReply)
		return ctx.Result(200, reply)
	}
}

type HelloworldHTTPClient interface {
	CreateGreeter(ctx context.Context, req *CreateGreeterRequest, opts ...http.CallOption) (rsp *CreateGreeterReply, err error)
	CreateGreeterWithCache(ctx context.Context, req *CreateGreeterRequest, opts ...http.CallOption) (rsp *CreateGreeterReply, err error)
	DeleteGreeter(ctx context.Context, req *DeleteGreeterRequest, opts ...http.CallOption) (rsp *DeleteGreeterReply, err error)
	DeleteGreeterWithCache(ctx context.Context, req *DeleteGreeterRequest, opts ...http.CallOption) (rsp *DeleteGreeterReply, err error)
	GetGreeter(ctx context.Context, req *GetGreeterRequest, opts ...http.CallOption) (rsp *GetGreeterReply, err error)
	GetGreeterWithCache(ctx context.Context, req *GetGreeterRequest, opts ...http.CallOption) (rsp *GetGreeterReply, err error)
	ListGreeter(ctx context.Context, req *ListGreeterRequest, opts ...http.CallOption) (rsp *ListGreeterReply, err error)
	ListGreeterWithCache(ctx context.Context, req *ListGreeterRequest, opts ...http.CallOption) (rsp *ListGreeterReply, err error)
	UpdateGreeter(ctx context.Context, req *UpdateGreeterRequest, opts ...http.CallOption) (rsp *UpdateGreeterReply, err error)
	UpdateGreeterWithCache(ctx context.Context, req *UpdateGreeterRequest, opts ...http.CallOption) (rsp *UpdateGreeterReply, err error)
}

type HelloworldHTTPClientImpl struct {
	cc *http.Client
}

func NewHelloworldHTTPClient(client *http.Client) HelloworldHTTPClient {
	return &HelloworldHTTPClientImpl{client}
}

func (c *HelloworldHTTPClientImpl) CreateGreeter(ctx context.Context, in *CreateGreeterRequest, opts ...http.CallOption) (*CreateGreeterReply, error) {
	var out CreateGreeterReply
	pattern := "/v1/greeter"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHelloworldCreateGreeter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *HelloworldHTTPClientImpl) CreateGreeterWithCache(ctx context.Context, in *CreateGreeterRequest, opts ...http.CallOption) (*CreateGreeterReply, error) {
	var out CreateGreeterReply
	pattern := "/v1/greeter_with_cache"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHelloworldCreateGreeterWithCache))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *HelloworldHTTPClientImpl) DeleteGreeter(ctx context.Context, in *DeleteGreeterRequest, opts ...http.CallOption) (*DeleteGreeterReply, error) {
	var out DeleteGreeterReply
	pattern := "/v1/greeter/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHelloworldDeleteGreeter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *HelloworldHTTPClientImpl) DeleteGreeterWithCache(ctx context.Context, in *DeleteGreeterRequest, opts ...http.CallOption) (*DeleteGreeterReply, error) {
	var out DeleteGreeterReply
	pattern := "/v1/greeter_with_cache/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHelloworldDeleteGreeterWithCache))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *HelloworldHTTPClientImpl) GetGreeter(ctx context.Context, in *GetGreeterRequest, opts ...http.CallOption) (*GetGreeterReply, error) {
	var out GetGreeterReply
	pattern := "/v1/greeter/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHelloworldGetGreeter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *HelloworldHTTPClientImpl) GetGreeterWithCache(ctx context.Context, in *GetGreeterRequest, opts ...http.CallOption) (*GetGreeterReply, error) {
	var out GetGreeterReply
	pattern := "/v1/greeter_with_cache/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHelloworldGetGreeterWithCache))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *HelloworldHTTPClientImpl) ListGreeter(ctx context.Context, in *ListGreeterRequest, opts ...http.CallOption) (*ListGreeterReply, error) {
	var out ListGreeterReply
	pattern := "/v1/greeter"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHelloworldListGreeter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *HelloworldHTTPClientImpl) ListGreeterWithCache(ctx context.Context, in *ListGreeterRequest, opts ...http.CallOption) (*ListGreeterReply, error) {
	var out ListGreeterReply
	pattern := "/v1/greeter_with_cache"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationHelloworldListGreeterWithCache))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *HelloworldHTTPClientImpl) UpdateGreeter(ctx context.Context, in *UpdateGreeterRequest, opts ...http.CallOption) (*UpdateGreeterReply, error) {
	var out UpdateGreeterReply
	pattern := "/v1/greeter/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHelloworldUpdateGreeter))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *HelloworldHTTPClientImpl) UpdateGreeterWithCache(ctx context.Context, in *UpdateGreeterRequest, opts ...http.CallOption) (*UpdateGreeterReply, error) {
	var out UpdateGreeterReply
	pattern := "/v1/greeter_with_cache/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationHelloworldUpdateGreeterWithCache))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
