// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-cinch/layout/internal/biz"
	"github.com/go-cinch/layout/internal/conf"
	"github.com/go-cinch/layout/internal/data"
	"github.com/go-cinch/layout/internal/server"
	"github.com/go-cinch/layout/internal/service"
	"github.com/go-kratos/kratos/v2"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data) (*kratos.App, func(), error) {
	dataData, cleanup := data.NewData(confData)
	greeterRepo := data.NewGreeterRepo(dataData)
	greeterUseCase := biz.NewGreeterUseCase(greeterRepo)
	hellowordService := service.NewHellowordService(greeterUseCase)
	grpcServer := server.NewGRPCServer(confServer, hellowordService)
	httpServer := server.NewHTTPServer(confServer, hellowordService)
	app := newApp(grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
